# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'microsoft'
        architecture: 'x64'
        cache: maven
    - name: Build FreeChatClient with Maven
      run: mvn -B package --file FreeChatClient/pom.xml
    - name: Build FreeCharServer with Maven
      run: mvn -B package --file FreeChatServer/pom.xml
    - name: show files
      run: ls -R
    - run: |
        echo "FreeChatClient"
        cd FreeChatClient
        ls -R
        cd ..
        echo "FreeChatServer"
        cd FreeChatServer
        ls -R
        cd ..
